services:
    form_handler.param_converter:
        class: Hostnet\Bundle\FormHandlerBundle\ParamConverter\FormParamConverter
        arguments:
            - "@service_container"
        tags:
            - { name: request.param_converter, priority: false, converter: form_information_converter }

    form_handler.provider.simple:
        class: Hostnet\Component\Form\Simple\SimpleFormProvider
        arguments:
            - "@form.factory"